# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    inputs:
      terraformVersion: '0.15.0'

  - task: TerraformCLI@0
    inputs:
      command: 'init'
      backendType: 'azurerm'
      backendServiceArm: 'Pay-As-You-Go(b5cf1a86-4412-4c53-8835-6f56a8258a58)'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'tf-pollinate-rg'
      backendAzureRmResourceGroupLocation: 'westus2'
      backendAzureRmStorageAccountName: 'tfpollinatestorage'
      backendAzureRmContainerName: 'tf-datadog-k8s-pollinate'
      backendAzureRmKey: 'tf.state'
      allowTelemetryCollection: true

  - task: TerraformTaskV1@0
    inputs:
      provider: 'azurerm'
      command: 'destroy'
      environmentServiceNameAzureRM: 'Pay-As-You-Go(b5cf1a86-4412-4c53-8835-6f56a8258a58)'
